### ISSUE TITLE
malo

### ISSUE THREAD

**Issue by PlinMartinez** [PlinMartinez/PliniBot-arbitraje#3]
arregla esto

**Comment by jpadron1983** [comment]
saludos estoy interesado en ayudar, se puede hacer con otro exchange??

**Comment by PlinMartinez** [comment]
Hola,
Es multiexchange y multitriangulos
En cuál estas pensandoen adaptarlo?

⁣Obtener BlueMail para Android ​

**Comment by PlinMartinez** [comment]
preuba
